model_params:
  pic_channels : 1
  pic_size : 28
  down_channels : [32, 64, 128, 256]
  mid_channels : [256, 256, 128]
  time_emb_dim : 128
  down_sample : [True, True, False]
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2
